#!/usr/bin/python
# -*- coding: utf-8 -*-
#File name: fetchData.py
#Author: sanfanling
#licence: GPL-V3 


from configparser import ConfigParser
import os.path



class fetchData:
    
    def __init__(self):
        fileName = "minesweeper.conf"
        if not os.path.exists(fileName):
            self.initConfigfile()
    
    def getData(self):
        self.cf = ConfigParser()
        self.cf.read(fileName)
        self.questionMark = self.cf.getboolean("options", "questionMark")
        self.autoStart = self.cf.getboolean("options", "autoStart")
        self.sound = self.cf.getboolean("options", "sound")
        
        self.gridSize = self.cf.getint("options", "gridSize")
        self.numberSize = self.cf.getint("options", "numberSize")
        
        for x in ("easy", "medium", "difficult"):
            exec("self.{}_totalGame = self.cf.getint('{}Mode', 'totalGame')".format(x, x))
            exec("self.{}_totalGame = self.cf.getint('{}Mode', 'winGame')".format(x, x))
            for y in range(1, 11):
                exec("self.{}_{} = self.cf.get('{}Mode', {})".format(x, y, x, y))
        
        
        
    
    def initConfigfile(self):
        conf = """
        ### this file is generated by application, recording all settings and statistics
        
        [options]
        questionMark = True
        autoStart = False
        sound = False
        gridSize = 25
        numberSize = 0
        
        
        [easyMode]
        1 = 
        2 = 
        3 = 
        4 =
        5 = 
        6 =
        7 =
        8 =
        9 =
        10 =
        totalGame = 0
        winGame = 0
        
        [mediumMode]
        1 = 
        2 = 
        3 = 
        4 =
        5 = 
        6 =
        7 =
        8 =
        9 =
        10 =
        totalGame = 0
        winGame = 0
        
        [difficultMode]
        1 = 
        2 = 
        3 = 
        4 =
        5 = 
        6 =
        7 =
        8 =
        9 =
        10 =
        totalGame = 0
        winGame = 0
        
        [custom]
        size = 10, 10, 10
        """
